### ISSUE TITLE
No way to extend logging with custom implimentation

### ISSUE THREAD

**Issue by Togusa09** [paypal/sdk-core-dotnet#41]
Currently the BaseLogger class is internal, preventing any custom logging implementations from inheriting from it.

Can this be made public so that we can add our own logging methods?

**Comment by jziaja** [comment]
Hi @Togusa09 , thanks for pointing this out!  There's no reason why the logging classes shouldn't be made public in this SDK.  I'll get this change made both here and the [PayPal .NET SDK](https://github.com/paypal/PayPal-NET-SDK). :)
