### ISSUE TITLE
Please update reference to Newtonsoft.Json to 7.0

### ISSUE THREAD

**Issue by horusin** [paypal/sdk-core-dotnet#44]
The current reference is not up to date with the latest release version of Newtonsoft.Json; causing assembly linking to break.

To avoid users having to manually add assembly binding rules, please update the reference to the latest Newtonsoft.Json release.

**Comment by juwlee** [comment]
Thanks for reporting @horusin . It seems to be the same issue as [this one](https://github.com/paypal/PayPal-NET-SDK/issues/110)

**Comment by horusin** [comment]
Yes, this is the same, but in this other package.
