### ISSUE TITLE
Please make the Logger Type delimiter dynamic through config

### ISSUE THREAD

**Issue by bwilliamsoncafepress** [paypal/sdk-core-dotnet#51]
I've written this enhancement, but do not have permission to push up a branch to do a pull-request. Please review and consider making this change so I do not have to maintain a fork for a very few lines of code that enables a very big benefit of using my own loggers. Thanks so much!

**File:** Source\SDK\Log\LogConfiguration.cs

Please see attachment for edit, renamed as txt for uploading here.

[LogConfiguration.txt](https://github.com/paypal/sdk-core-dotnet/files/607994/LogConfiguration.txt)

**Comment by pp-randy** [comment]
If you have a change in your fork, would you be able to submit a pull request?  I can have the SDK team review it further.
