### ISSUE TITLE
How Can I use this sdk for recurring payment? Can you please provide the documentation for it?

### ISSUE THREAD

**Issue by arielnaveenchopra** [paypal/sdk-core-dotnet#52]

**Comment by pp-randy** [comment]
I would recommend using the REST API SDK for .net here https://github.com/paypal/PayPal-NET-SDK
Look over https://developer.paypal.com/docs/api/payments.billing-plans
You can find samples for Billing Plans and Billing Agreements here: https://github.com/paypal/PayPal-NET-SDK/tree/develop/Samples/Source

Billing Agreements is the REST API equivalent of a Classic API recurring payment.

**Comment by pp-randy** [comment]
If you do require the Classic API the SDK you want is https://github.com/paypal/merchant-sdk-dotnet

This particular repository contains objects common to some other dotnet sdks.
