### ISSUE TITLE
Invalid HTTP response Unable to connect to the remote server after change to 'security-test-sandbox'

### ISSUE THREAD

**Issue by mh884** [paypal/sdk-core-dotnet#55]
### General information

* SDK/Library version:  1.7.1
* Environment: security-test-sandbox 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: dotNET45

### Issue description

An exception of type 'PayPal.Exception.ConnectionException' occurred in PayPalCoreSDK.dll but was not handled in user code
Additional information: Invalid HTTP response Unable to connect to the remote server

**Comment by bluk** [comment]
The `security-test-sandbox` endpoint is no longer available. You can use `sandbox` instead as PayPal API sandbox should only be accepting TLS 1.2 connections. I've updated the README to remove the outdated note.
