### ISSUE TITLE
Comma splitter prevents using a custom Logger

### ISSUE THREAD

**Issue by mikeatdjp** [paypal/sdk-core-dotnet#61]
https://github.com/paypal/sdk-core-dotnet/blob/ad29a433c4093d31183b7987b4a0521da655f068/Source/SDK/Log/LogConfiguration.cs#L18

We would like to use our custom Logger inheriting from PayPal.BaseLogger, but to do so we have to use a fully qualified Assembly name in the appSetting.  Fully qualified assembly names have a comma, and using a comma for the splitter limits custom Loggers to the one supplied in the PayPal assembly which is log4net.

**Comment by devchristina** [comment]
Closing issue as not planned, repo is archived.
